### ISSUE TITLE
No options in Sonoma

### ISSUE THREAD

**Issue by mrgooge** [liquidx/webviewscreensaver#79] opened 2024-02-02 05:18 UTC
I can install, but when I try to use, I never get OPTIONS to allow me to enter a URL?

**Comment by coofercat** [comment] 2024-02-02 17:45
I had the same - it may be caused by quarantine. Did you use the --no-quarantine in brew, or otherwise authorise the application?

It may also just need you to close down settings and go back into it again (or possibly flick to another settings screen, then back to Screen Saver).

**Comment by mrgooge** [comment] 2024-02-02 18:07
Hi coofercat, Thanks for the reply and info! I needed to update to the latest version, then used Allow through Security to make Options appear... Now the actual interface in Options is kind of broken.

**Comment by agologan** [comment] 2024-03-13 12:09
Not sure what you mean by broken.
New v2.3 version is now available with better Sonoma support.

Closing, but feel free to reply if you have further details and I'll reopen the issue.

**Closed by agologan** 2024-03-13 12:09 UTC
