### ISSUE TITLE
How to interact with page to set appropriate cookies/local storage?

### ISSUE THREAD

**Issue by is-digital-services** [liquidx/webviewscreensaver#42] opened 2017-09-27 13:09 UTC
Thanks for the awesome screensaver.  I'm using it as an information radiator for my software team, displaying a build monitor that jenkins provides for us.  I am challenged though as the build monitor plugin allows for the web user to set settings in terms of number of columns and font size.  This is stored in the browser cache.  I can't figure out a way to have set the browser cache for the webviewscreensaver browser because when I go to click the button the the page, the screen saver turns off.  If there a way to interact with a web page using the webviewscreensaver in order to prime browser cache values in an interactive way?

**Comment by joshboyden** [comment] 2017-09-27 16:25
@is-digital-services I also ran into this, but I think this is a duplicate of issue #31 .

**Comment by agologan** [comment] 2024-03-13 17:33
It's now possible to preview an entry and interact with the website during configuration with version `v2.3+`

**Closed by agologan** 2024-03-13 17:33 UTC
